// Generated by build_data.py — do not edit by hand
window.REPORT = {
 "meta": {
  "total": 100000,
  "date_min": "2025-07-14",
  "date_max": "2026-07-13",
  "generated": "2026-07-14"
 },
 "locations": [
  {
   "key": "Canggu",
   "ko": "짱구",
   "posts": 14213,
   "avg_likes": 2509,
   "avg_comments": 99,
   "focus": true
  },
  {
   "key": "Seminyak",
   "ko": "스미냑",
   "posts": 14444,
   "avg_likes": 2506,
   "avg_comments": 100,
   "focus": true
  },
  {
   "key": "Ubud",
   "ko": "우붓",
   "posts": 14149,
   "avg_likes": 2497,
   "avg_comments": 100,
   "focus": false
  },
  {
   "key": "Kuta",
   "ko": "꾸따",
   "posts": 14232,
   "avg_likes": 2495,
   "avg_comments": 100,
   "focus": false
  },
  {
   "key": "Uluwatu",
   "ko": "울루와뚜",
   "posts": 14319,
   "avg_likes": 2494,
   "avg_comments": 99,
   "focus": false
  },
  {
   "key": "Nusa Penida",
   "ko": "누사페니다",
   "posts": 14427,
   "avg_likes": 2500,
   "avg_comments": 99,
   "focus": false
  },
  {
   "key": "Jimbaran",
   "ko": "짐바란",
   "posts": 14216,
   "avg_likes": 2535,
   "avg_comments": 101,
   "focus": false
  }
 ],
 "monthly": {
  "months": [
   "2025-08",
   "2025-09",
   "2025-10",
   "2025-11",
   "2025-12",
   "2026-01",
   "2026-02",
   "2026-03",
   "2026-04",
   "2026-05",
   "2026-06"
  ],
  "canggu": [
   1171,
   1143,
   1181,
   1188,
   1328,
   1240,
   1086,
   1147,
   1156,
   1184,
   1174
  ],
  "seminyak": [
   1318,
   1134,
   1243,
   1215,
   1207,
   1253,
   1141,
   1210,
   1212,
   1184,
   1171
  ],
  "min": 1086,
  "max": 1328,
  "note": "부분 수집 월(2025-07, 2026-07)은 제외"
 },
 "media": {
  "canggu": [
   {
    "key": "image",
    "count": 4763,
    "pct": 33.5
   },
   {
    "key": "video",
    "count": 4740,
    "pct": 33.3
   },
   {
    "key": "carousel",
    "count": 4710,
    "pct": 33.1
   }
  ],
  "seminyak": [
   {
    "key": "image",
    "count": 4949,
    "pct": 34.3
   },
   {
    "key": "video",
    "count": 4866,
    "pct": 33.7
   },
   {
    "key": "carousel",
    "count": 4629,
    "pct": 32.0
   }
  ],
  "labels": {
   "image": "이미지",
   "video": "영상",
   "carousel": "캐러셀"
  }
 },
 "hashtags": {
  "canggu": [
   {
    "tag": "#짱구",
    "count": 4339
   },
   {
    "tag": "#balitrip",
    "count": 4330
   },
   {
    "tag": "#explorebali",
    "count": 4326
   },
   {
    "tag": "#balilife",
    "count": 4320
   },
   {
    "tag": "#balitravel",
    "count": 4265
   },
   {
    "tag": "#baliindonesia",
    "count": 4251
   }
  ],
  "seminyak": [
   {
    "tag": "#우붓",
    "count": 4420
   },
   {
    "tag": "#스미냑",
    "count": 4415
   },
   {
    "tag": "#explorebali",
    "count": 4373
   },
   {
    "tag": "#bali",
    "count": 4371
   },
   {
    "tag": "#짱구",
    "count": 4367
   },
   {
    "tag": "#발리여행",
    "count": 4310
   }
  ]
 },
 "compare": {
  "canggu": {
   "posts": 14213,
   "avg_likes": 2509,
   "median_likes": 2514,
   "max_likes": 5000,
   "avg_comments": 99,
   "video_share": 33.3
  },
  "seminyak": {
   "posts": 14444,
   "avg_likes": 2506,
   "median_likes": 2515,
   "max_likes": 4999,
   "avg_comments": 100,
   "video_share": 33.7
  }
 },
 "research": {
  "surf": {
   "category": "surf",
   "scene_summary_ko": "짱구(Canggu)는 발리 서핑의 중심지로, 바투볼롱·올드맨스·버라와·에코비치 등 초보자 친화적인 비치브레이크가 몰려 있어 입문 강습과 서핑캠프가 가장 활발합니다. Kima, Wave House, Soleia, Elsewhere처럼 숙박·매일 강습·영상 분석을 하나로 묶은 올인클루시브 서양식 캠프가 많고, 인디안써머(롱보드)와 인다서프처럼 한국어 지원이 되는 캠프도 확실히 자리를 잡았습니다. 스미냑(더블식스·66비치)은 짱구보다 서핑 씬 자체는 작지만 Santai 같은 ASI 공인 초보 강습 스쿨이 탄탄합니다. 다만 발리 서핑 업장은 개폐업과 이전이 잦으니, 방문 전 카카오톡·인스타그램 등으로 현재 운영 여부와 일정을 꼭 확인하는 것이 좋습니다.",
   "venues": [
    {
     "name": "Indian Summer Bali (Longboard Surf Camp)",
     "area": "Canggu (Batu Bolong)",
     "type_ko": "서핑캠프 (롱보드 전문)",
     "google_rating": null,
     "price_hint_ko": "데이 세션 약 5만~10만원(원화 기준), 숙박 포함 주간 패키지는 5~20% 할인",
     "highlights_ko": [
      "한국인(Parco)이 2016년부터 운영, 한국어 강습·카카오톡 예약 가능",
      "싱글핀 롱보드 전문 — 초보부터 행파이브·행텐까지 레벨업",
      "이른 아침 도패트롤 후 오전에 일정 종료, 4K 60fps 영상 리뷰",
      "컨디션에 따라 바투볼롱 외 꾸따·짐바란·스랑안 등으로 이동"
     ],
     "why_ko": "짱구에서 몇 안 되는 한국인 운영 롱보드 전문 캠프로, 언어 장벽 없이 한국어로 세심한 코칭과 영상 피드백을 받고 싶은 여행자에게 잘 맞습니다.",
     "best_for_ko": "초보~중급, 롱보드 입문, 한국어 강습 선호",
     "korean_friendly": true,
     "sources": [
      "https://www.insumbali.com/kr",
      "https://www.insumbali.com/",
      "https://www.tripadvisor.com/Attraction_Review-g311298-d15674748-Reviews-Indian_Summer_Bali_Longboard_Surf_Camp-Canggu_North_Kuta_Bali.html"
     ],
     "status_note_ko": "트립어드바이저 등 영어권 리뷰는 거의 없고 인스타그램·카카오톡 중심으로 운영되니, 최신 일정·예약은 카카오톡으로 확인 권장.",
     "price_usd_ko": "데이 세션 $40~75",
     "lat": -8.6523,
     "lng": 115.1435,
     "geo_precision": "approx",
     "instagram": "@surf.insum.bali"
    },
    {
     "name": "In Da Surf Camp & School Bali",
     "area": "Canggu (Kayu Tulang)",
     "type_ko": "서핑캠프 & 스쿨 (숙박 포함)",
     "google_rating": null,
     "price_hint_ko": "세미프라이빗(강사 1인당 2명) 레슨 1회 약 75만 루피아, 서프&스테이 도미토리 1박 약 108만~152만 루피아",
     "highlights_ko": [
      "강사 1인당 최대 2명 세미프라이빗 + 영상 분석 포함",
      "숙박·식사·커뮤니티가 어우러진 가족적인 분위기",
      "컨디션 따라 스팟 이동, 이론 강습 제공",
      "한국어 웹사이트·한국인 후기 다수 (단, 강습은 주로 영어)"
     ],
     "why_ko": "짱구에서 코칭 퀄리티와 커뮤니티 분위기로 평이 매우 좋은 올라운드 캠프로, 숙박까지 한 번에 해결하고 싶은 초·중급 여행자에게 추천합니다.",
     "best_for_ko": "초보~중급, 숙박형 캠프, 소수정예 강습",
     "korean_friendly": true,
     "sources": [
      "https://www.indasurf.com/kr",
      "https://www.indasurf.com/",
      "https://www.tripadvisor.com/Attraction_Review-g311298-d6584173-Reviews-In_Da_Surf_Camp_School_Bali-Canggu_North_Kuta_Bali.html"
     ],
     "status_note_ko": null,
     "price_usd_ko": "레슨 ~$45 · 숙박 $65~95/박",
     "lat": -8.649855,
     "lng": 115.1372183,
     "geo_precision": "exact",
     "instagram": "@in_da_surfbali"
    },
    {
     "name": "Kima Surf Camp Canggu",
     "area": "Canggu (Echo Beach/Pererenan 인근, 해변 250m)",
     "type_ko": "서핑캠프 (리조트형)",
     "google_rating": 4.9,
     "price_hint_ko": "숙박 등급별 주간 올인클루시브 패키지(도미토리~럭셔리 빌라); 정확 요금은 시즌·객실별 상이",
     "highlights_ko": [
      "짱구 최대 규모의 리조트형 캠프 — 수영장 3개·짐·15m 클라이밍월",
      "하루 2회 서핑 가이딩, 전 레벨 대응",
      "전 세계 여행자와 어울리는 활발한 사교 분위기",
      "구글 평점 4.9 (725+ 리뷰)"
     ],
     "why_ko": "시설과 국제적인 사교 분위기를 중시한다면 가장 안정적인 대형 캠프 선택지입니다.",
     "best_for_ko": "초보~상급, 시설·사교 분위기 중시",
     "korean_friendly": false,
     "sources": [
      "https://kimasurf.com/canggu-surfresort",
      "https://wanderlog.com/place/details/2211869/kima-surf-camp-bali-canggu",
      "https://thesurfatlas.com/bali-surf/surf-camps-in-canggu/"
     ],
     "status_note_ko": null,
     "lat": -8.65522,
     "lng": 115.129483,
     "geo_precision": "exact",
     "instagram": "@kimasurf"
    },
    {
     "name": "Wave House Surf Camp",
     "area": "Canggu",
     "type_ko": "서핑캠프 (디자인 호텔형)",
     "google_rating": 4.8,
     "price_hint_ko": "숙박+매일 강습 묶은 올인클루시브 주간 패키지 위주(정확 요금은 시즌별 상이)",
     "highlights_ko": [
      "디자인 호텔 감성의 세련된 공간과 라이스필드 뷰",
      "하루 2세션, 강사 대 게스트 2~3:1, 영상 분석·이론 수업",
      "초보 진도가 빠르다는 후기 다수",
      "구글 평점 4.8 (500+ 리뷰)"
     ],
     "why_ko": "코칭 체계와 숙소 퀄리티의 균형이 좋아, 편안한 환경에서 제대로 배우고 싶은 여행자에게 적합합니다.",
     "best_for_ko": "초보~중급, 코칭 퀄리티·숙소 감성 중시",
     "korean_friendly": false,
     "sources": [
      "https://wavehousebali.com/canggu/camp",
      "https://wanderlog.com/place/details/68149/wave-house-surf-camp-in-canggu-bali",
      "https://www.tripadvisor.com/Hotel_Review-g311298-d2187731-Reviews-Wave_House_Surf_Camp-Canggu_North_Kuta_Bali.html"
     ],
     "status_note_ko": null,
     "lat": -8.66599,
     "lng": 115.143456,
     "geo_precision": "exact",
     "instagram": "@wavehousebali"
    },
    {
     "name": "Sōleïa Surf Camp Bali",
     "area": "Canggu (Berawa/Batu Bolong)",
     "type_ko": "서핑캠프 (올인클루시브)",
     "google_rating": null,
     "price_hint_ko": "1박 약 €63~110 (식사·매일 강습·요가·장비 포함 올인클루시브)",
     "highlights_ko": [
      "가성비 좋은 올인클루시브 + ISA 공인 코칭",
      "버라와·올드맨스·바투볼롱 등 초·중급 스팟 활용",
      "젊고 사교적인 분위기, 수영장 보유",
      "식사·요가·장비 포함"
     ],
     "why_ko": "합리적인 가격에 숙박·강습·요가까지 묶여 있어 처음 서핑캠프를 경험하는 젊은 여행자에게 인기입니다.",
     "best_for_ko": "초보, 가성비, 젊은 사교 분위기",
     "korean_friendly": false,
     "sources": [
      "https://www.soleiasurf.com/",
      "https://thesurfatlas.com/bali-surf/surf-camps-in-canggu/",
      "https://www.hostelworld.com/hostels/p/319734/soleia-surf/"
     ],
     "status_note_ko": "호스텔월드 평점은 9.4/10로 높으나 표본(리뷰 수)이 적어 참고용; 구글 평점 수치는 미확인.",
     "price_usd_ko": "올인클루시브 $70~120/박",
     "lat": -8.6558763,
     "lng": 115.1424103,
     "geo_precision": "exact",
     "instagram": "@soleiasurf"
    },
    {
     "name": "Pelan Pelan Bali (Surf & Yoga Retreat)",
     "area": "Canggu 외곽 (Cemagi/Tabanan 방면)",
     "type_ko": "서핑 & 요가 리트릿",
     "google_rating": 4.9,
     "price_hint_ko": "8일 패키지에 요가 4회·마사지 3회 등 포함되는 패키지 위주 요금",
     "highlights_ko": [
      "서핑과 하타 요가·명상·마사지를 결합한 힐링형 리트릿",
      "인근 마을 출신 현지 강사, 전 레벨 환영",
      "조용한 라이스필드 환경",
      "구글 평점 4.9 (235 리뷰)"
     ],
     "why_ko": "번잡한 시내 대신 차분한 환경에서 서핑과 요가로 몸과 마음을 함께 리셋하고 싶은 여행자에게 좋습니다.",
     "best_for_ko": "초보~전 레벨, 서핑+요가 힐링",
     "korean_friendly": false,
     "sources": [
      "https://pelanbali.com/",
      "https://wanderlog.com/place/details/2485658/pelan-pelan-bali-surf-camp--yoga-retreat",
      "https://www.tripadvisor.com/Hotel_Review-g311298-d7149655-Reviews-Pelan_Pelan_Surf_and_Yoga_Retreat-Canggu_North_Kuta_Bali.html"
     ],
     "status_note_ko": "짱구 중심가에서 떨어진 외곽(체마기/타바난 경계)이라 시내 접근성은 다소 낮음.",
     "lat": -8.624444,
     "lng": 115.107291,
     "geo_precision": "exact",
     "instagram": "@pelanbali"
    },
    {
     "name": "Elsewhere Surf Camps Bali",
     "area": "Canggu (중심부)",
     "type_ko": "서핑캠프 (파티·사교형, 18세 이상)",
     "google_rating": null,
     "price_hint_ko": "숙박+매일 강습+영상 분석 포함 올인클루시브 패키지",
     "highlights_ko": [
      "18세 이상 대상 사교·파티 중심 캠프",
      "강사 대 게스트 2:1 매일 강습 + 매일 영상 분석",
      "수영장 2개·바·루프탑 테라스, 테마 디너 등 이벤트 다수",
      "짱구 중심부 위치"
     ],
     "why_ko": "서핑과 함께 활발한 파티·소셜 분위기를 즐기고 싶은 젊은 솔로 여행자에게 잘 맞습니다.",
     "best_for_ko": "18+ 젊은 층, 파티·사교 분위기",
     "korean_friendly": false,
     "sources": [
      "https://elsewheresurfcamps.com/bali/",
      "https://thesurfatlas.com/bali-surf/surf-camps-in-canggu/"
     ],
     "status_note_ko": "구글 등 독립 플랫폼의 공식 평점 수치는 확인되지 않음(자체 홍보 리뷰 위주)이니 참고 요망.",
     "lat": -8.650686,
     "lng": 115.133721,
     "geo_precision": "exact",
     "instagram": "@elsewheresurfcamps"
    },
    {
     "name": "Santai Surf School Bali",
     "area": "Seminyak (Double Six Beach)",
     "type_ko": "서핑스쿨 (강습 전문)",
     "google_rating": 4.8,
     "price_hint_ko": "2시간 그룹 레슨 약 50만 루피아(약 £25, 4~5만원) 수준; 프라이빗·세미프라이빗 옵션 별도",
     "highlights_ko": [
      "발리 유일의 ASI 공인 스쿨, 2012년부터 가족 경영",
      "더블식스 비치 — 초·중급 프라이빗/세미/그룹 레슨",
      "트립어드바이저 우수상 6년·명예의 전당 등 다년간 수상",
      "구글 평점 4.8 (188 리뷰)"
     ],
     "why_ko": "스미냑 숙소에 머무는 초보자가 안전하고 체계적으로 입문하기 좋은 스미냑 대표 스쿨입니다.",
     "best_for_ko": "초보자, 가족 단위, 스미냑 숙박객",
     "korean_friendly": false,
     "sources": [
      "https://www.tripadvisor.com/Attraction_Review-g469404-d4373202-Reviews-Santai_Surf_School_Bali-Seminyak_Kuta_District_Bali.html",
      "https://wanderlog.com/place/details/845332/santai-surf-school-bali",
      "https://www.academyofsurfing.com/schools/santai-surf-school-bali/surf"
     ],
     "status_note_ko": null,
     "price_usd_ko": "그룹레슨 $28~35",
     "lat": -8.698092,
     "lng": 115.161925,
     "geo_precision": "exact",
     "instagram": "@santai_surf_bali"
    }
   ],
   "top_pick": {
    "name": "Indian Summer Bali (Longboard Surf Camp)",
    "reason_ko": "한국인이 운영해 한국어로 코칭과 예약(카카오톡)이 가능한 짱구의 대표 롱보드 캠프라, 언어 부담 없이 제대로 배우고 싶은 한국 여행자에게 1순위입니다. 숏보드·전 레벨 올라운드 캠프를 원하면 In Da Surf, 대형 시설·사교 분위기를 원하면 Kima, 스미냑 숙박 기반 초보 강습이면 Santai가 좋은 대안입니다."
   }
  },
  "run": {
   "category": "run",
   "scene_summary_ko": "짱구·스미냑은 발리에서 러닝 씬이 가장 뜨거운 지역으로, 새벽마다 힙한 카페 앞에 모여 3~8km를 함께 뛰고 커피로 마무리하는 '카페 런클럽' 문화가 자리 잡았다. 대부분 무료에 사전등록 없이 그냥 나타나면 되고, 현지인·외국인·여행자가 자연스럽게 섞여 소셜 목적으로도 인기다. 짱구·프레레난 쪽은 Nomas(NRC)·Rise Run처럼 새벽 로드/해변 러닝이 강세고, 스미냑은 Potato Head·Ku De Ta 같은 비치클럽이 주최하는 웰빙형 런클럽이 특징이다. 클럽이 부담스럽다면 논밭 사이 Subak 포장길과 세미냑 해변이 혼자 뛰기 좋은 대표 코스다.",
   "venues": [
    {
     "name": "Nomas Run Club (NRC)",
     "area": "Pererenan / Canggu",
     "type_ko": "러닝클럽",
     "schedule_ko": "월 오전 6:30 (Runamuk, 3~6km) · 수 오전 6:30 (Rite Bali, 인터벌) · 금 오전 7:00 (Kynd Community, 5km)",
     "meeting_point_ko": "월: Runamuk Bali (Pererenan) / 수: Rite Bali / 금: Kynd Community (Canggu)",
     "price_hint_ko": "무료 (등록 없이 그냥 나타나면 됨)",
     "highlights_ko": [
      "발리에서 가장 핫한 러닝 커뮤니티 중 하나",
      "Runamuk·Kynd 등 힙한 카페에서 집결 후 커피 소셜",
      "3~6km, 초보도 부담 없는 페이스",
      "현지인·외국인·여행자가 섞이는 국제적 분위기"
     ],
     "why_ko": "짱구 특유의 '카페+러닝+소셜' 문화를 가장 제대로 경험할 수 있는 곳으로, 혼자 온 여행자가 친구 만들기에 최적이다. 요일마다 다른 감성 카페에서 출발하는 것도 매력.",
     "best_for_ko": "소셜, 카페 러닝, 초보 러너",
     "instagram": "@nomasrunclub",
     "sources": [
      "https://www.instagram.com/nomasrunclub/",
      "https://bali.live/p/running-clubs-in-bali",
      "https://cinchy.life/en/blog/running-communities-in-bali"
     ],
     "status_note_ko": "요일별 집결 카페가 바뀔 수 있으니 인스타 최신 공지를 당일 확인 권장",
     "lat": -8.657524,
     "lng": 115.134442,
     "geo_precision": "exact"
    },
    {
     "name": "Rise Run Bali (Rise & Run)",
     "area": "Canggu / Seseh",
     "type_ko": "러닝클럽",
     "schedule_ko": "화 오전 6:15 (4/8km) · 목 오전 6:15 (스피드) · 금 오전 6:15 (6km, Seseh) · 일 오전 7:00 (장소 매주 변경)",
     "meeting_point_ko": "화: The Goat Father / 목: The Dog House Canggu / 금: Just Oats Seseh / 일: 순환 (인스타 공지)",
     "price_hint_ko": "무료 (사전등록 불필요, 그냥 참석)",
     "highlights_ko": [
      "주 4회로 스케줄이 가장 다양",
      "새벽 해변·로드 러닝, 4/8km 거리 선택 가능",
      "Strava 클럽·WhatsApp 그룹 운영으로 정보 얻기 쉬움",
      "모든 레벨 환영"
     ],
     "why_ko": "일정과 거리 옵션이 가장 많아 자기 컨디션에 맞춰 골라 뛰기 좋다. 매주 요일이 고정돼 있어 여행 일정에 끼워 넣기 편하다.",
     "best_for_ko": "새벽러닝, 다양한 코스, 모든 레벨",
     "instagram": "@riserunbali",
     "sources": [
      "https://www.riserunbali.com/",
      "https://www.riserunbali.com/schedule",
      "https://bali.live/p/running-clubs-in-bali"
     ],
     "status_note_ko": "일요일 집결 장소는 매주 바뀌므로 인스타/사이트 스케줄 페이지 확인",
     "lat": -8.648649,
     "lng": 115.1372,
     "geo_precision": "exact"
    },
    {
     "name": "Canggu Run Club",
     "area": "Canggu",
     "type_ko": "러닝클럽",
     "schedule_ko": "매주 화·목 오후 5시",
     "meeting_point_ko": "Jalan Raya Semat, Canggu (S2S CrossFit과 공동 운영)",
     "price_hint_ko": "무료로 알려짐",
     "highlights_ko": [
      "드물게 저녁(오후 5시) 러닝 — 새벽 기상이 힘든 사람에게 유리",
      "외국인·디지털노마드 비중이 높은 국제적 분위기",
      "편안한 페이스와 쉬운 코스",
      "S2S CrossFit과 연계된 커뮤니티"
     ],
     "why_ko": "짱구 대부분 런클럽이 새벽인 반면 이곳은 오후 5시라 늦잠·시차 여행자도 참여하기 좋다. 가볍게 소셜 러닝을 원하는 사람에게 추천.",
     "best_for_ko": "저녁 러닝, 외국인·디지털노마드 소셜",
     "instagram": "@canggu_runclub",
     "sources": [
      "https://www.instagram.com/canggu_runclub/",
      "https://bali.live/p/running-clubs-in-bali"
     ],
     "status_note_ko": "팔로워 규모가 크지 않아 운영 빈도가 유동적일 수 있음 — 인스타 최신 게시물로 활동 여부 확인 권장",
     "lat": -8.6585456,
     "lng": 115.1400546,
     "geo_precision": "exact"
    },
    {
     "name": "Desa Run Club (Potato Head)",
     "area": "Seminyak",
     "type_ko": "러닝클럽",
     "schedule_ko": "매주 금 오전 6:30 (WITA), 약 5km",
     "meeting_point_ko": "Amphitheatre, Desa Potato Head (Jl. Petitenget No.51B, Seminyak)",
     "price_hint_ko": "무료 (러닝 후 전통 허브음료 자무(jamu) 제공)",
     "highlights_ko": [
      "5km 소셜 런, 경쟁보다 웰빙 지향",
      "가이드 쿨다운 + 전통 자무(jamu) 제공",
      "포테이토헤드의 세련된 비치클럽 시설에서 집결",
      "초보·여행자 친화적 분위기"
     ],
     "why_ko": "스미냑 숙소 여행자가 걸어서 접근하기 좋고, 러닝 후 자무·쿨다운까지 챙겨주는 웰빙 콘셉트라 러닝 초보에게도 부담이 없다.",
     "best_for_ko": "웰빙·소셜, 초보 러너, 스미냑 숙소",
     "instagram": "@potatoheadbali",
     "sources": [
      "https://seminyak.potatohead.co/experience/desa-run-club",
      "https://cinchy.life/en/blog/running-communities-in-bali"
     ],
     "status_note_ko": "요일·시간이 변동될 수 있어 Potato Head 이벤트 페이지/인스타(@potatoheadbali)에서 최신 확인 권장",
     "lat": -8.679435,
     "lng": 115.149934,
     "geo_precision": "exact"
    },
    {
     "name": "Seminyak Sunrise Runclub (Ku De Ta x The Compound)",
     "area": "Seminyak",
     "type_ko": "러닝클럽",
     "schedule_ko": "토요일 오전 7시 (매주가 아닌 특정 주말에만 운영)",
     "meeting_point_ko": "Ku De Ta, Seminyak (Petitenget) 출발 → The Compound 경유 5km 해안 루프",
     "price_hint_ko": "무료 (완주 후 Ku De Ta 커피/차 + The Compound 20% 바우처)",
     "highlights_ko": [
      "해안선을 따라 도는 5km 선라이즈 루프",
      "완주 후 Ku De Ta 커피·차 무료 제공",
      "The Compound 짐/카페 20% 할인 바우처",
      "여유롭고 포용적인 페이스"
     ],
     "why_ko": "세계적으로 유명한 Ku De Ta 비치클럽에서 출발하는 특별한 선라이즈 런으로, 스미냑 럭셔리 감성과 러닝을 함께 즐기고 싶은 여행자에게 어울린다.",
     "best_for_ko": "새벽러닝, 스미냑 비치클럽 감성",
     "instagram": "@kudetabali",
     "sources": [
      "https://kudeta.com/event/seminyak-running-club/",
      "https://kudeta.com/stories/seminyak-sunrise-running-club/"
     ],
     "status_note_ko": "상시 주간 모임이 아니라 특정 토요일에만 열리는 이벤트성 런클럽(예: 2026년 7월 25일). 방문 전 Ku De Ta 이벤트 페이지에서 날짜·사전예약 필수 확인",
     "lat": -8.6872409,
     "lng": 115.1545772,
     "geo_precision": "exact"
    },
    {
     "name": "Pererenan Rice Field Run (Subak Uma Desa track)",
     "area": "Pererenan / Canggu",
     "type_ko": "러닝코스",
     "schedule_ko": null,
     "meeting_point_ko": "Jalan Subak Uma Desa (Plawa Guesthouse 인근), Pererenan",
     "price_hint_ko": "무료",
     "highlights_ko": [
      "논밭(subak) 사이를 가르는 콘크리트 포장길, 편도 약 1.3~2.7km",
      "차량 거의 없고 평탄해 인터벌·초보 러닝에 최적",
      "일출·일몰 논밭 뷰, 곳곳에 정자(bale bengong)",
      "메인 Batu Bolong 거리보다 훨씬 한산"
     ],
     "why_ko": "런클럽 시간과 안 맞아도 혼자 뛰기 좋은 짱구 대표 코스로, 평탄하고 조용해 페이스 훈련이나 가벼운 아침 조깅 모두 적합하다.",
     "best_for_ko": "혼자 새벽러닝, 초보, 논밭 뷰",
     "instagram": null,
     "sources": [
      "https://finnsbeachclub.com/guides/jogging-bali/",
      "https://cinchy.life/en/blog/spots-for-jogging-in-canggu-bali",
      "https://greatruns.com/bali-canggu-rice-paddies/"
     ],
     "status_note_ko": "새벽 6시 이전 출발 시 헤드램프 권장, 오전 7시 이전이 가장 시원함",
     "lat": -8.628344,
     "lng": 115.148994,
     "geo_precision": "approx"
    },
    {
     "name": "Seminyak Beach Run",
     "area": "Seminyak",
     "type_ko": "러닝코스",
     "schedule_ko": null,
     "meeting_point_ko": "Seminyak Beach (예: Ku De Ta / La Plancha 앞)에서 해변을 따라 남쪽 Kuta 방향",
     "price_hint_ko": "무료",
     "highlights_ko": [
      "해변을 따라 편도 최대 7km, 모래·포장 혼합 구간",
      "일출·일몰 바다 뷰, 서퍼·요가 인파 구경",
      "Kuta·Segara Beach 방향으로 거리 연장 가능",
      "스미냑 숙소에서 바로 접근"
     ],
     "why_ko": "스미냑에 묵는 여행자가 숙소에서 나와 바로 바다를 끼고 뛸 수 있는 코스로, 일출·일몰 시간대 뷰가 특히 좋다.",
     "best_for_ko": "일출·일몰 러닝, 스미냑 숙소, 바다 뷰",
     "instagram": null,
     "sources": [
      "https://finnsbeachclub.com/guides/jogging-bali/",
      "https://www.thebalibible.com/guides/the-runner-s-guide-to-bali-beaches-trails-crews-worth-knowing"
     ],
     "status_note_ko": "썰물 시간대가 달리기 편하고, 한낮 더위·자외선은 피할 것",
     "lat": -8.691193,
     "lng": 115.157141,
     "geo_precision": "exact"
    }
   ],
   "top_pick": {
    "name": "Nomas Run Club (NRC)",
    "reason_ko": "무료·초보 친화·소셜의 삼박자를 모두 갖춘 짱구 대표 런클럽으로, 힙한 카페에서 모여 3~6km 뛰고 커피로 마무리하는 발리 러닝 문화의 정수를 혼자 온 여행자도 쉽게 즐길 수 있다. 주 3회 운영이라 일정 맞추기도 수월하다."
   }
  },
  "wellness": {
   "category": "wellness",
   "scene_summary_ko": "짱구(Canggu)는 발리 웰니스·피트니스 씬의 중심으로, 좁은 지역 안에 요가원·크로스핏·복싱·무에타이 짐과 회복시설(사우나·아이스배스)이 빽빽하게 모여 있어 '아침 요가 → 낮 웨이트/크로스핏 → 저녁 무에타이'가 하루에 가능하다. 스미냑(Seminyak)은 쇼핑·비치클럽과 가까운 접근성 좋은 요가원과 오래된 무에타이 짐 위주로, 짱구만큼 밀도가 높지는 않지만 도심형 웰니스에 적합하다. 프리미엄 시설(Nirvana Life, Body Factory)은 하루 이용권이 60만 루피아를 넘기도 하지만, 대부분의 요가·격투 드롭인은 15만~37만 루피아 선에서 단발 체험이 가능하다. 전반적으로 영어가 잘 통하고 외국인·디지털노마드 커뮤니티가 커서 초보 여행자도 진입장벽이 낮은 편이다. 짱구·스미냑의 헬스장 씬은 이미 리포트에 담은 Nirvana Life나 Body Factory 같은 고급 웰니스형 짐(데이패스 20만~35만 루피아대) 외에도 선택지가 상당히 두텁다. 세계·유럽 파워리프팅 챔피언이 지도하는 하드코어 웨이트 짐, 짱구 유일의 24시간 짐, 데이패스 5만~10만 루피아의 가성비 짐, 그리고 그룹 클래스 중심의 스미냑 로컬 짐까지 폭이 넓어 예산·운동 스타일·체류 기간에 맞춰 고를 수 있다. 다만 짱구의 로컬·가성비 짐은 에어컨 없이 대형 선풍기로 돌리는 오픈에어 구조가 많아 한낮에는 더울 수 있으니, 더위에 민감하면 에어컨 완비 여부를 꼭 확인하는 게 좋다.",
   "venues": [
    {
     "name": "The Practice",
     "subcategory": "yoga",
     "area": "Batu Bolong (Canggu)",
     "google_rating": 4.5,
     "price_hint_ko": "드롭인 1회 약 15만 루피아 (KITAS 11만, 현지인 8만)",
     "highlights_ko": [
      "전통 하타·프라나야마 중심의 '요가 사원' 콘셉트",
      "바뚜볼롱 비치 도보권의 아름다운 공간",
      "세계적 수준의 티처진",
      "초보부터 심화까지 레벨 다양"
     ],
     "why_ko": "짱구에서 가장 명성 높은 정통 요가원으로, 피트니스형 스튜디오와 달리 깊이 있는 전통 수련을 원하는 사람에게 최적이다.",
     "best_for_ko": "정통 하타 요가·진지한 수련",
     "sources": [
      "https://www.thepracticebali.com/practice-with-us/rates/",
      "https://www.allyogatraining.com/best-yoga-studios-canggu"
     ],
     "status_note_ko": null,
     "price_usd_ko": "드롭인 $9~10",
     "lat": -8.65609,
     "lng": 115.13226,
     "geo_precision": "exact",
     "instagram": "@thepractice.official"
    },
    {
     "name": "Samadi Bali",
     "subcategory": "yoga",
     "area": "Canggu",
     "google_rating": 4.6,
     "price_hint_ko": "드롭인 1회 약 14만 루피아부터",
     "highlights_ko": [
      "아쉬탕가·마이소르 스타일이 중심",
      "유기농 카페·주말 오가닉 마켓 병설",
      "수상 큐브형 스튜디오와 열대 정원",
      "요가 티처 트레이닝(TTC) 운영"
     ],
     "why_ko": "정통 아쉬탕가 커뮤니티가 탄탄하고 카페·마켓까지 한 곳에 모여 있어, 수련과 발리 웰니스 라이프스타일을 함께 즐기기 좋다.",
     "best_for_ko": "아쉬탕가·마이소르 수련자",
     "sources": [
      "https://www.tripadvisor.com/Attraction_Review-g311298-d6556407-Reviews-Samadi_Bali_Yoga_Health_Hub-Canggu_North_Kuta_Bali.html",
      "https://www.yogahub.id/studios/samadi-bali"
     ],
     "status_note_ko": null,
     "price_usd_ko": "드롭인 $8~10",
     "lat": -8.64411,
     "lng": 115.13724,
     "geo_precision": "exact",
     "instagram": "@samadiyogacanggu"
    },
    {
     "name": "Yoga 108 Bali",
     "subcategory": "yoga",
     "area": "Seminyak",
     "google_rating": 4.6,
     "price_hint_ko": "드롭인(워크인) 1회 약 15만 루피아",
     "highlights_ko": [
      "예약 없이 워크인 가능한 접근성",
      "하타·인·빈야사·아쉬탕가 등 데일리 클래스",
      "초보자에게 친절한 지도로 호평",
      "스미냑 중심의 편리한 위치"
     ],
     "why_ko": "스미냑에서 부담 없이 드롭인할 수 있는 대표 요가원으로, 쇼핑·비치클럽 일정과 병행하기 좋고 초보자 친화적이다.",
     "best_for_ko": "초보·스미냑 숙소 여행자",
     "sources": [
      "https://www.yoga108bali.com/seminyak-yoga-studio-schedule-prices/",
      "https://www.tripadvisor.com/Attraction_Review-g469404-d10064537-Reviews-Yoga_108_Bali-Seminyak_Kuta_District_Bali.html"
     ],
     "status_note_ko": null,
     "price_usd_ko": "드롭인 $9~10",
     "lat": -8.68975,
     "lng": 115.16246,
     "geo_precision": "exact",
     "instagram": "@yoga108bali"
    },
    {
     "name": "Nirvana Life (formerly Nirvana Strength)",
     "subcategory": "gym",
     "area": "Canggu",
     "google_rating": null,
     "price_hint_ko": "데이패스 약 66만 루피아++ (회복시설·수영장·전 시설 포함), 주간권 약 220만 루피아++",
     "highlights_ko": [
      "과거 'Nirvana Strength'로 알려진 프리미엄 소셜 웰니스 클럽",
      "스트렝스·클래스·회복(사우나·아이스배스)·수영장 종합 시설",
      "'발리 최고의 짐'으로 자주 언급",
      "코치·커뮤니티 만족도가 매우 높음"
     ],
     "why_ko": "훈련부터 회복, 커뮤니티까지 한 곳에서 해결하는 올인원 프리미엄 클럽으로, 시설·분위기·코칭 모두 상위권으로 평가된다.",
     "best_for_ko": "종합 트레이닝·회복 중시",
     "sources": [
      "https://nirvanalife.com/bali/nirvana-life-membership/",
      "https://abrotherabroad.com/nirvana-life-bali/"
     ],
     "status_note_ko": "'Nirvana Strength'에서 'Nirvana Life'로 리브랜딩됨",
     "price_usd_ko": "데이패스 $40~50 (세금별도)",
     "lat": -8.64264,
     "lng": 115.15436,
     "geo_precision": "exact",
     "instagram": "@nirvanalifebali"
    },
    {
     "name": "Body Factory Bali",
     "subcategory": "gym",
     "area": "Canggu (Jl. Nelayan, Berawa 인근)",
     "google_rating": null,
     "price_hint_ko": "짐 전용 월 멤버십 약 270만 루피아~ (프리미엄 가격대), 단기 이용권은 별도 문의",
     "highlights_ko": [
      "최신 장비를 갖춘 대형 프리미엄 짐",
      "사우나·콜드플런지 등 회복시설",
      "커뮤니티 런·이벤트 활발",
      "가격대는 높은 편(뉴욕 Equinox에 비유되기도)"
     ],
     "why_ko": "장비·회복시설·커뮤니티 삼박자가 좋은 짱구 대표 프리미엄 짐으로, 제대로 된 웨이트 트레이닝 환경을 원하는 사람에게 적합하다.",
     "best_for_ko": "진지한 웨이트·프리미엄 시설 선호",
     "sources": [
      "https://www.bodyfactorybali.com/",
      "https://johnnyafrica.com/body-factory-bali-review/"
     ],
     "status_note_ko": "프리미엄 가격대이므로 단기 방문 시 드롭인/주간권 조건을 사전 확인 권장",
     "price_usd_ko": "월 $170~ · 단기권 문의",
     "lat": -8.65601,
     "lng": 115.13489,
     "geo_precision": "exact",
     "instagram": "@bodyfactory_bali"
    },
    {
     "name": "Wanderlust Fitness Village (CrossFit Wanderlust)",
     "subcategory": "crossfit",
     "area": "Canggu",
     "google_rating": null,
     "price_hint_ko": "데이패스 약 20만~25만 루피아 (하루 무제한)",
     "highlights_ko": [
      "발리 최대 규모의 크로스핏·HYROX 시설",
      "주 50개 이상 클래스(크로스핏·메트콘·복싱·모빌리티 등)",
      "수영장·사우나·아이스배스 등 대형 회복존",
      "커뮤니티 에너지가 강점"
     ],
     "why_ko": "크로스핏·HYROX를 제대로 즐기고 싶은 사람에게 최적인 대형 시설로, 클래스 종류와 회복존 규모가 압도적이다.",
     "best_for_ko": "크로스핏·HYROX·진지한 트레이닝",
     "sources": [
      "https://classpass.com/studios/wanderlust-fitness-village-bali",
      "https://www.tripadvisor.com/Attraction_Review-g311298-d12231826-Reviews-CrossFit_Wanderlust-Canggu_North_Kuta_Bali.html"
     ],
     "status_note_ko": "대형 클래스 특성상 개인 코칭 밀도는 낮을 수 있다는 후기가 있음",
     "price_usd_ko": "데이패스 $13~16",
     "lat": -8.6417,
     "lng": 115.1563,
     "geo_precision": "exact",
     "instagram": "@wanderlustfitnessvillage_bali"
    },
    {
     "name": "CrossFit Canggu (at Fortitude Bali)",
     "subcategory": "crossfit",
     "area": "Canggu (Tibubeneng)",
     "google_rating": 5,
     "price_hint_ko": "신규회원 첫 1개월 무제한 약 US$84, 멤버십 전 단발 드롭인 체험 가능",
     "highlights_ko": [
      "발리 유일의 루프탑 크로스핏 박스",
      "파노라마 전망 속 고강도 트레이닝",
      "부티크 규모의 끈끈한 커뮤니티",
      "가입 전 단발 클래스 체험 가능"
     ],
     "why_ko": "루프탑 뷰와 소규모 부티크 분위기가 매력으로, 대형 시설보다 아담하고 커뮤니티 밀착형 크로스핏을 원하면 좋다.",
     "best_for_ko": "크로스핏 입문·소규모 커뮤니티 선호",
     "sources": [
      "https://fortitudebali.com/crossfit-canggu/",
      "https://fortitudebali.com/schedule-pricing/"
     ],
     "status_note_ko": null,
     "price_usd_ko": "첫 달 무제한 ~$84",
     "lat": -8.66005,
     "lng": 115.13975,
     "geo_precision": "exact",
     "instagram": "@fortitudebali"
    },
    {
     "name": "Bali MMA",
     "subcategory": "boxing",
     "area": "Canggu (Padonan)",
     "google_rating": null,
     "price_hint_ko": "단발 1클래스 약 20만 루피아, 1일 무제한 약 35만 루피아 (월 300만 루피아)",
     "highlights_ko": [
      "무에타이·복싱·BJJ·MMA 종합 격투 아카데미",
      "풀사이즈 복싱링·MMA 케이지·대형 에어컨 그래플링룸",
      "아이스배스·사우나 등 회복시설",
      "폭스스포츠 선정 아시아 5위 MMA 짐"
     ],
     "why_ko": "여러 격투 종목을 한 곳에서 배울 수 있는 발리 대표 종합 격투 아카데미로, 시설·코치 수준이 최상위권이다.",
     "best_for_ko": "종합 격투·진지한 트레이닝",
     "sources": [
      "https://balimma.com/memberships/",
      "https://finnsbeachclub.com/guides/bali-gyms-boxing-muay-thai-mma/"
     ],
     "status_note_ko": null,
     "price_usd_ko": "클래스 $13~22",
     "lat": -8.64163,
     "lng": 115.15585,
     "geo_precision": "exact",
     "instagram": "@balimma"
    },
    {
     "name": "Soma Fight Club",
     "subcategory": "boxing",
     "area": "Canggu (Tibubeneng)",
     "google_rating": null,
     "price_hint_ko": "드롭인 단발 약 37.5만 루피아 / 데이패스 약 30만 루피아",
     "highlights_ko": [
      "복싱·무에타이·킥복싱 특화 스트라이킹 짐",
      "자체 파이트 나이트(대회) 개최",
      "아이스배스·사우나 등 회복시설 우수",
      "90분 패드워크 등 밀도 높은 클래스"
     ],
     "why_ko": "스트라이킹에 특화된 인기 격투 짐으로, 파이트 나이트 문화와 고급 시설을 갖춰 타격 훈련에 집중하고 싶은 사람에게 좋다.",
     "best_for_ko": "복싱·무에타이 타격 특화",
     "sources": [
      "https://somafightclub.com/collections/membership",
      "https://abrotherabroad.com/soma-fight-club-bali-muay-thai-boxing-gym/"
     ],
     "status_note_ko": "인기가 많아 그룹 클래스가 붐빌 수 있고 가격대는 높은 편",
     "price_usd_ko": "드롭인 $19~24",
     "lat": -8.64373,
     "lng": 115.15733,
     "geo_precision": "exact",
     "instagram": "@somafightclub"
    },
    {
     "name": "Zealot Muay Thai",
     "subcategory": "boxing",
     "area": "Canggu (Semat)",
     "google_rating": null,
     "price_hint_ko": null,
     "highlights_ko": [
      "무에타이 전문 스튜디오",
      "프로 파이터 Jeremias Abraham이 운영",
      "자카르타에 본점을 둔 브랜드"
     ],
     "why_ko": "무에타이 한 종목에 집중하는 전문 짐으로, 프로 파이터가 직접 운영해 정통 무에타이를 배우기 좋다.",
     "best_for_ko": "무에타이 집중 트레이닝",
     "sources": [
      "https://finnsbeachclub.com/guides/bali-gyms-boxing-muay-thai-mma/",
      "https://www.muaythaimap.com/cities/bali"
     ],
     "status_note_ko": "드롭인 가격은 방문 전 확인 권장",
     "lat": -8.62156,
     "lng": 115.117,
     "geo_precision": "exact",
     "instagram": "@zealotmuaythaibali"
    },
    {
     "name": "Dee Muay Thai",
     "subcategory": "boxing",
     "area": "Seminyak (Kerobokan)",
     "google_rating": null,
     "price_hint_ko": "합리적인 가격대(정확 금액은 현장 확인)",
     "highlights_ko": [
      "스미냑 중심의 오래된 무에타이 짐",
      "관광객·현지인·교민 모두에게 친숙",
      "초보부터 진지한 선수까지 수용",
      "가격이 저렴한 편"
     ],
     "why_ko": "스미냑에서 오래 사랑받아온 무에타이 짐으로, 접근성이 좋고 가격 부담이 적어 가볍게 체험하기 좋다.",
     "best_for_ko": "초보·스미냑 숙소 여행자",
     "sources": [
      "https://finnsbeachclub.com/guides/bali-gyms-boxing-muay-thai-mma/",
      "https://mejirogymbali.com/blog/best-fighting-gym-bali/"
     ],
     "status_note_ko": null,
     "lat": -8.66776,
     "lng": 115.16937,
     "geo_precision": "exact",
     "instagram": "@deemuaythai_bali"
    },
    {
     "name": "Fitness Plus Canggu",
     "subcategory": "gym",
     "area": "Canggu (Berawa/Tanah Barak)",
     "google_rating": 4.4,
     "price_hint_ko": "데이패스 20만 루피아(약 1.7만원), 월 회원권은 출처별로 50만~150만 루피아로 엇갈림",
     "highlights_ko": [
      "짱구에서 사실상 유일한 24시간 운영 짐 (심야·새벽 운동 가능)",
      "에어컨 완비, 청결하게 관리된다는 평",
      "덤벨 50kg까지·스쿼트랙 2개·머신 구비, 2층에 스핀바이크·복싱백, 사우나",
      "규모가 작아 피크타임엔 장비 대기 발생"
     ],
     "why_ko": "시차 적응이 안 됐거나 낮에 다른 일정이 있는 여행자에게 24시간 운영과 에어컨 조합이 큰 장점이다. 고급 짐들이 못 채우는 '아무 때나·저렴하게·시원하게' 니즈를 20만 루피아 데이패스로 정확히 메운다.",
     "best_for_ko": "24시간·에어컨",
     "sources": [
      "https://bali.live/places/fitness-plus-1",
      "https://inivie.com/discover-bali/gyms-in-canggu",
      "https://johnnyafrica.com/best-gyms-bali-canggu-seminyak-kuta-ubud/"
     ],
     "status_note_ko": "데이패스(20만)는 여러 출처에서 일관되나 월 회원권 가격은 50만~150만 루피아로 상이하니 방문 전 재확인 권장.",
     "price_usd_ko": "데이패스 $12~13 (24시간)",
     "lat": -8.649297,
     "lng": 115.135697,
     "geo_precision": "exact",
     "instagram": "@fitnessplus.canggu"
    },
    {
     "name": "Bull Gym Bali",
     "subcategory": "gym",
     "area": "Canggu (Tibubeneng)",
     "google_rating": 4.5,
     "price_hint_ko": "데이패스 20만~25만 루피아(약 1.7만~2.1만원), 주간·월간권 별도",
     "highlights_ko": [
      "파워리프팅에 특화된 하드코어 웨이트 짐 (파워랙·바벨·스쿼트 스탠드 충실)",
      "세계·유럽 파워리프팅 챔피언 출신 트레이너 상주",
      "에어컨 없음, 대형 선풍기로 환기 / 프로틴 바 운영",
      "월~토 07-21시, 일 07-14시 / 구글 4.5(276리뷰)"
     ],
     "why_ko": "진지하게 웨이트·스트렝스를 파고드는 사람에게 최적이다. Nirvana Life·Body Factory의 인플루언서 감성보다 순수한 훈련 분위기를 원한다면 이곳이 정답에 가깝다.",
     "best_for_ko": "웨이트·파워리프팅 집중",
     "sources": [
      "https://bullgym-balicanggu.com/rates/",
      "https://wanderlog.com/place/details/2449228/bull-gym-bali-fitness",
      "https://johnnyafrica.com/best-gyms-bali-canggu-seminyak-kuta-ubud/"
     ],
     "status_note_ko": null,
     "price_usd_ko": "데이패스 $13~16",
     "lat": -8.643724,
     "lng": 115.157146,
     "geo_precision": "exact",
     "instagram": "@bullgymbali"
    },
    {
     "name": "Pucuk Bali Gym",
     "subcategory": "gym",
     "area": "Canggu (Batu Bolong)",
     "google_rating": 4.8,
     "price_hint_ko": "데이패스 약 5만~10만 루피아(최근 인상), 주간 17.5만·월 30만~40만 루피아",
     "highlights_ko": [
      "짱구 최고 가성비 짐 (특히 주간·월간권이 매우 저렴)",
      "발리 전통 건축의 오픈에어 구조, 선풍기 냉방",
      "데드리프트존·올림픽 스쿼트랙 등 신형 장비, 샤워·와이파이",
      "구글 평점 4.8(369리뷰)로 로컬 짐 중 최상위, 조용하고 쾌적"
     ],
     "why_ko": "장기 체류하며 매일 운동할 여행자에게 비용 대비 최고다. 오픈에어라 한낮엔 덥지만 아침·저녁엔 쾌적하고, 평점이 4.8로 로컬 짐 중 가장 높다.",
     "best_for_ko": "가성비",
     "sources": [
      "https://wanderlog.com/place/details/7583482/pucuk-bali-gym",
      "https://mindtrip.ai/attraction/canggu-bali/pucuk-bali-gym/at-MPWgqpxI",
      "https://thetravellingwellnessgirl.com/the-best-affordable-gyms-in-bali-for-backpackers/"
     ],
     "status_note_ko": "데이패스가 과거 3.5만~5만에서 최근 10만 루피아로 오른 정황이 있으니 방문 전 현재가 확인 권장. 주간·월간권은 여전히 저렴한 편.",
     "price_usd_ko": "데이패스 $3~7 · 주간권 ~$11",
     "lat": -8.651173,
     "lng": 115.13541,
     "geo_precision": "exact",
     "instagram": "@pucukbali_gym"
    },
    {
     "name": "Bali Fitness Seminyak",
     "subcategory": "gym",
     "area": "Seminyak (Sunset Road)",
     "google_rating": null,
     "price_hint_ko": "데이패스 15만 루피아(약 1.3만원), 주간 40만·월 70만 루피아",
     "highlights_ko": [
      "스미냑 대표 그룹 피트니스 짐 (2010년 오픈, 발리 최초 Les Mills 클래스)",
      "스미냑 최초 사이클 스튜디오·STARTRAC 장비",
      "프리웨이트존과 그룹 클래스 병행, 가입비 없음",
      "데이패스에 전 그룹 클래스 참여 포함"
     ],
     "why_ko": "웨이트만이 아니라 그룹 클래스(레미밀즈·사이클)를 함께 즐기고 싶은 여행자에게 좋다. 스미냑 중심부라 접근성이 좋고 데이패스에 클래스가 포함돼 가성비도 준수하다.",
     "best_for_ko": "스미냑 그룹 클래스 겸용",
     "sources": [
      "https://www.balifitness.asia/prices",
      "https://www.tripadvisor.com/Attraction_Review-g469404-d6866703-Reviews-Bali_Fitness_Seminyak-Seminyak_Kuta_District_Bali.html",
      "https://www.baliholidaysecrets.com/gyms-in-seminyak/"
     ],
     "status_note_ko": "공식 사이트 정보가 다소 오래됨(운영시간 미표기)이나 트립어드바이저에 2026년 후기가 있어 정상 영업 중으로 보임 — 방문 전 운영시간만 재확인 권장.",
     "price_usd_ko": "데이패스 $9~10 (클래스 포함)",
     "lat": -8.687601,
     "lng": 115.170913,
     "geo_precision": "exact",
     "instagram": "@balifitnessseminyak"
    },
    {
     "name": "Daily Gym Bali",
     "subcategory": "gym",
     "area": "Seminyak (Petitenget)",
     "google_rating": 4.3,
     "price_hint_ko": "세션(데이)패스 약 10만 루피아부터(약 0.85만원)",
     "highlights_ko": [
      "스미냑 실속형 가성비 짐 (세션패스 10만 루피아~)",
      "층별로 웨이트·케이블 머신 + 복싱/무에타이(복싱 링) 겸비",
      "에어컨 없음, 선풍기 (한낮엔 더운 편)",
      "초보자 친화적·부담 없는 분위기, 주 7일 운영"
     ],
     "why_ko": "스미냑에서 저렴하게 웨이트와 격투기 운동을 함께 하고 싶을 때 실속 있는 선택이다. 화려한 시설은 없지만 장비가 충실하고 트레이너 실력이 좋다는 평이 많다.",
     "best_for_ko": "스미냑 가성비",
     "sources": [
      "https://www.tripadvisor.com/Attraction_Review-g469404-d17562893-Reviews-Daily_Gym_Bali-Seminyak_Kuta_District_Bali.html",
      "https://www.top-rated.online/cities/Kerobokan+Klod/place/p/3529094/Daily+Gym+Bali",
      "https://finnsbeachclub.com/guides/bali-seminyak-best-gyms/"
     ],
     "status_note_ko": "웨이트 중심이지만 복싱·무에타이 비중도 큰 하이브리드형 — 순수 웨이트만 원하면 참고.",
     "price_usd_ko": "세션 $6~8",
     "lat": -8.676927,
     "lng": 115.154254,
     "geo_precision": "exact",
     "instagram": "@dailygymbali"
    },
    {
     "name": "Wrong Gym",
     "subcategory": "gym",
     "area": "Pererenan (짱구 인근)",
     "google_rating": 4.6,
     "price_hint_ko": "데이패스 30만~45만 루피아(약 2.5만~3.8만원, 프리미엄)",
     "highlights_ko": [
      "프리미엄 웰니스형 짐 (수영장·자쿠지·사우나·아이스바스·스팀룸)",
      "신형 장비 충실, 06-22시 주 7일 운영",
      "구글 4.6(787리뷰)로 평판 우수",
      "Body Factory보다 살짝 저렴한 가격대"
     ],
     "why_ko": "이미 다룬 Body Factory·Nirvana Life식 '고급 헬스+회복시설' 조합을 조금 더 저렴하게 경험하려는 사람에게 대안이다. 페레레난 위치라 짱구 북부·페레레난 숙소에 특히 편리하다.",
     "best_for_ko": "프리미엄·회복시설 겸용",
     "sources": [
      "https://wronggym.com/pages/memberships",
      "https://www.tripadvisor.com/Attraction_Review-g5323528-d26663038-Reviews-The_Wrong_Gym-Pererenan_Canggu_North_Kuta_Bali.html",
      "https://johnnyafrica.com/wrong-gym-bali-review/"
     ],
     "status_note_ko": "데이패스가 비싼 프리미엄 가격대이며, 인플루언서 위주 분위기라는 후기도 있음.",
     "price_usd_ko": "데이패스 $19~28",
     "lat": -8.649225,
     "lng": 115.123192,
     "geo_precision": "exact",
     "instagram": "@thewronggym"
    }
   ],
   "top_picks": {
    "yoga": {
     "name": "The Practice",
     "reason_ko": "짱구 최고 명성의 정통 요가원으로, 드롭인 15만 루피아로 부담 없이 세계적 수준의 하타 수련을 경험할 수 있다."
    },
    "crossfit": {
     "name": "Wanderlust Fitness Village",
     "reason_ko": "발리 최대 규모의 크로스핏·HYROX 시설로 클래스와 회복존이 압도적이라 크로스핏 목적 여행자에게 1순위. 종합 웰니스 짐을 원하면 Nirvana Life가 프리미엄 대안이다."
    },
    "boxing": {
     "name": "Bali MMA",
     "reason_ko": "무에타이·복싱·BJJ·MMA를 한 곳에서 배울 수 있는 최상위 종합 격투 아카데미로, 단발 20만 루피아로 진입도 쉽다. 타격 특화를 원하면 Soma Fight Club을 추천한다."
    },
    "gym": {
     "name": "Fitness Plus Canggu",
     "reason_ko": "짱구에서 사실상 유일한 24시간 짐이면서 에어컨까지 완비돼, 이미 리포트에 있는 Nirvana Life·Body Factory 같은 고급 짐(비싸고 24시간이 아님)이 못 채우는 '아무 때나·저렴하게·시원하게'라는 여행자 니즈를 정확히 메운다. 데이패스 20만 루피아로 시차 적응 중 새벽 운동도 가능하다. 순수하게 웨이트에 집중하고 싶으면 Bull Gym(파워리프팅), 예산을 최대한 아끼려면 Pucuk Bali Gym(주간·월간권 최저가)을 함께 고려하면 된다."
    }
   }
  },
  "spots": {
   "category": "spots",
   "scene_summary_ko": "짱구(Canggu)는 서핑 문화와 힙한 카페, 개성 있는 비치클럽이 밀집한 발리에서 가장 트렌디한 지역으로, 배라와(Berawa)·바투볼롱(Batu Bolong)·프레레난(Pererenan) 등 세부 동네마다 분위기가 조금씩 다릅니다. 바로 옆 스미냑(Seminyak)은 좀 더 세련되고 고급스러운 분위기로 선셋 다이닝과 비치바가 강점입니다. 두 지역 모두 서향 해안이라 매일 저녁 인도양으로 지는 일몰이 최고의 하이라이트이며, 해변·비치클럽·카페가 스쿠터로 가까워 반나절이면 여러 곳을 묶어 다닐 수 있습니다. 짱구에서 차로 15~30분이면 타나롯 사원, 누아누 크리에이티브 시티 같은 근교 명소도 반나절 코스로 다녀올 수 있습니다.",
   "venues": [
    {
     "name": "Batu Bolong Beach",
     "subcategory": "beach",
     "area": "Batu Bolong",
     "google_rating": null,
     "price_hint_ko": "무료 (서프보드 렌탈 약 10만 IDR/일, 서핑 레슨 50~70만 IDR)",
     "highlights_ko": [
      "짱구 서핑·카페 문화의 중심 해변",
      "부드러운 파도로 서핑 입문자에게 최적",
      "해변가 와룽·카페에서 선셋 맥주",
      "올드맨스·에코비치까지 도보권"
     ],
     "why_ko": "짱구를 처음 왔다면 반드시 들르는 메인 해변으로, 서핑 구경과 카페, 일몰을 한자리에서 즐길 수 있습니다.",
     "best_for_ko": "서핑 입문·선셋",
     "sources": [
      "https://canggu.holidayinnresorts.com/blog/batu-bolong-beach",
      "https://www.sunshineseeker.com/destinations/canggu-batu-bolong-beach/",
      "https://cinchy.life/en/blog/batu-bolong-beach-canggu"
     ],
     "status_note_ko": "성수기·주말 매우 붐빔",
     "price_usd_ko": "무료 · 보드렌탈 ~$6/일 · 레슨 $30~45",
     "lat": -8.659482,
     "lng": 115.130136,
     "geo_precision": "exact"
    },
    {
     "name": "Echo Beach (Batu Mejan)",
     "subcategory": "beach",
     "area": "Canggu",
     "google_rating": null,
     "price_hint_ko": "무료 (해변 와룽 나시고렝·미고렝 저렴)",
     "highlights_ko": [
      "중급 이상 서퍼를 위한 리프 브레이크",
      "줄지어 선 와룽에서 저렴한 일몰 맥주",
      "바투볼롱보다 한적하고 로컬한 분위기",
      "라브리사 비치클럽 바로 앞"
     ],
     "why_ko": "파도가 세서 서핑 구경하기 좋고, 해변 와룽에서 부담 없이 로컬한 일몰을 즐기기 좋습니다.",
     "best_for_ko": "서핑구경·선셋",
     "sources": [
      "https://mondosurfvillage.com/canggu-travel-guide-2026/echo-beach-canggu-guide/",
      "https://www.sunshineseeker.com/destinations/echo-beach-canggu/",
      "https://finnsbeachclub.com/guides/echo-beach-bali/"
     ],
     "status_note_ko": null,
     "price_usd_ko": "무료 · 와룽 식사 $2~5",
     "lat": -8.653732,
     "lng": 115.123778,
     "geo_precision": "exact"
    },
    {
     "name": "Seminyak Beach (Double Six)",
     "subcategory": "beach",
     "area": "Seminyak",
     "google_rating": null,
     "price_hint_ko": "무료 (비치바 음료 맥주 6~8만·칵테일 12~18만 IDR)",
     "highlights_ko": [
      "약 3km 이어지는 황금빛 모래사장",
      "더블식스~쁘띠뜽엣 구간 대표 일몰 명소",
      "컬러풀한 빈백 비치바와 라이브 음악",
      "쁘띠뜽엣 사원 실루엣 포토스팟"
     ],
     "why_ko": "스미냑 도심에서 바로 걸어 나가는 선셋 해변으로, 비치바에 앉아 노을과 라이브 음악을 즐기기 좋습니다.",
     "best_for_ko": "선셋·비치바",
     "sources": [
      "https://www.baliholidaysecrets.com/seminyak-beach/",
      "https://balirescentre.com/articles/double-six-beach/",
      "https://www.ohana-agency.com/blog/seminyak-beach"
     ],
     "status_note_ko": "이안류 있음 - 라이프가드 깃발 구역에서만 물놀이 권장",
     "price_usd_ko": "무료 · 음료 $4~11",
     "lat": -8.697541,
     "lng": 115.162138,
     "geo_precision": "exact"
    },
    {
     "name": "FINNS Beach Club",
     "subcategory": "beachclub",
     "area": "Berawa",
     "google_rating": null,
     "price_hint_ko": "입장료 없음, 좌석 예약비/미니멈 저비수기 약 65만 IDR부터 (바·레스토랑 좌석은 미니멈 없음)",
     "highlights_ko": [
      "구글 4.1만+ 평가, 발리에서 리뷰 가장 많은 비치클럽",
      "365일 DJ·파티, 인피니티 풀 2개",
      "서비스 만족도가 특히 높음",
      "2026년 VIP 파티존 오픈"
     ],
     "why_ko": "발리 비치클럽의 대명사로, 활기찬 파티 분위기와 훌륭한 서비스를 원한다면 1순위로 꼽힙니다.",
     "best_for_ko": "파티·풀·선셋",
     "sources": [
      "https://bestbeachclubsbali.com/reviews/finns-beach-club-review/",
      "https://finnsbeachclub.com/guides/best-beach-club-bali/",
      "https://bestbeachclubsbali.com/faqs/finns-or-atlas/"
     ],
     "status_note_ko": null,
     "price_usd_ko": "입장 무료 · 좌석 미니멈 $40~ (성수기 상향)",
     "lat": -8.666765,
     "lng": 115.139398,
     "geo_precision": "exact",
     "instagram": "@finnsbeachclub"
    },
    {
     "name": "Atlas Beach Fest",
     "subcategory": "beachclub",
     "area": "Berawa",
     "google_rating": 4.7,
     "price_hint_ko": "입장료 평일 워크인 약 15만 IDR, 데이패스 약 30만 IDR(웰컴드링크·풀 이용 포함)",
     "highlights_ko": [
      "세계 최대 규모를 표방하는 비치클럽",
      "초대형 풀과 워터폴, 다양한 푸드마켓",
      "밤에는 슈퍼클럽으로 변신",
      "구글 4.7 (1.5만+ 리뷰)"
     ],
     "why_ko": "규모와 화려함으로 압도하는 곳으로, 사진과 먹거리·엔터테인먼트를 한 번에 즐기고 싶을 때 좋습니다.",
     "best_for_ko": "인생샷·파티·규모",
     "sources": [
      "https://atlasbeachfest.com/",
      "https://www.tripadvisor.com/Attraction_Review-g311298-d28453056-Reviews-Atlas_Beach_Club-Canggu_North_Kuta_Bali.html",
      "https://www.getyourguide.com/atlas-beach-club-l191222/entry-tickets-tc123/"
     ],
     "status_note_ko": "성수기 매우 붐비고 가격·서비스 만족도는 다소 엇갈리는 편",
     "price_usd_ko": "입장 $9~19 (데이패스 포함)",
     "lat": -8.665529,
     "lng": 115.138124,
     "geo_precision": "exact",
     "instagram": "@atlasbeachfest"
    },
    {
     "name": "La Brisa",
     "subcategory": "beachclub",
     "area": "Canggu",
     "google_rating": 4.6,
     "price_hint_ko": "입장료 없음, 좌석별 미니멈스펜드 (빈백 2인 약 60만 IDR, 오후 4시 이전 미니멈 없음)",
     "highlights_ko": [
      "폐어선 500척으로 지은 보헤미안 감성 건축",
      "곳곳이 포토스팟 - 한 걸음마다 인생샷",
      "에코비치 정면 선셋 뷰",
      "수영장 2개"
     ],
     "why_ko": "짱구에서 가장 감성적인 비치클럽으로, 보헤미안 인테리어와 일몰이 어우러져 한국 여행자 인생샷 성지로 꼽힙니다.",
     "best_for_ko": "인생샷·선셋",
     "sources": [
      "https://labrisa-bali.com/",
      "https://www.travelswithmissy.com/la-brisa-bali/",
      "https://elsky-bali.com/en/2025/07/14/beach-club-labrisa-en/",
      "https://bestbeachclubsbali.com/reviews/la-brisa-beach-club-review/"
     ],
     "status_note_ko": "선셋 시간대 대기 길고 미니멈스펜드 정책이 다소 헷갈린다는 후기 있음",
     "price_usd_ko": "미니멈 2인 $35~40 · 16시 이전 무료",
     "lat": -8.6542178,
     "lng": 115.1250199,
     "geo_precision": "exact",
     "instagram": "@labrisabali"
    },
    {
     "name": "Potato Head Beach Club",
     "subcategory": "beachclub",
     "area": "Petitenget",
     "google_rating": 4.6,
     "price_hint_ko": "데이베드 미니멈 300~400만 IDR(주류 포함), 미니멈 없는 무료 입장 좌석도 있음",
     "highlights_ko": [
      "음악·예술·디자인·웰니스가 결합된 크리에이티브 빌리지",
      "상징적인 인피니티 풀과 일몰",
      "지속가능성·디자인으로 세계적으로 유명",
      "구글 4.6 (1.3만+ 리뷰)"
     ],
     "why_ko": "스미냑을 대표하는 세련된 비치클럽으로, 디자인과 일몰, 음악을 고급스럽게 즐기고 싶을 때 좋습니다.",
     "best_for_ko": "선셋·디자인·풀",
     "sources": [
      "https://seminyak.potatohead.co/feast/beach-club",
      "https://bestbeachclubsbali.com/reviews/potato-head-beach-club-review/",
      "https://www.katiecaftravel.com/potato-head-beach-club/"
     ],
     "status_note_ko": null,
     "price_usd_ko": "무료석 있음 · 데이베드 $185~250",
     "lat": -8.679435,
     "lng": 115.149934,
     "geo_precision": "exact",
     "instagram": "@potatoheadbali"
    },
    {
     "name": "La Plancha",
     "subcategory": "beachclub",
     "area": "Seminyak",
     "google_rating": null,
     "price_hint_ko": "입장료 없음, 음료값만 (맥주 6~8만·칵테일 12~18만 IDR)",
     "highlights_ko": [
      "알록달록 레인보우 빈백과 파라솔",
      "스미냑 해변 대표 선셋 포토스팟",
      "캐주얼한 비치바, 부담 없는 가격",
      "오후 4:30~5:30 도착 추천"
     ],
     "why_ko": "화려한 컬러 빈백이 상징인 캐주얼 비치바로, 저렴하게 인생샷과 일몰을 동시에 즐기려는 한국 여행자에게 인기입니다.",
     "best_for_ko": "인생샷·선셋",
     "sources": [
      "https://laplancha-bali.com/",
      "https://elsky-bali.com/en/beach-club-la-plancha-bali-en/",
      "https://www.baliholidaysecrets.com/la-plancha/"
     ],
     "status_note_ko": null,
     "price_usd_ko": "무료 · 음료 $4~11",
     "lat": -8.6945086,
     "lng": 115.1597708,
     "geo_precision": "exact",
     "instagram": "@laplanchabali"
    },
    {
     "name": "Crate Cafe",
     "subcategory": "cafe",
     "area": "Batu Bolong",
     "google_rating": 4.2,
     "price_hint_ko": "가성비 좋은 브런치 (스무디볼·아보카도 토스트 등), 06:00~16:00",
     "highlights_ko": [
      "짱구 브런치 성지, 인더스트리얼 감성 인테리어",
      "푸짐한 스무디볼과 커피",
      "오전 8~10시 매우 붐빔",
      "예약 불가 워크인만 가능"
     ],
     "why_ko": "짱구의 아침을 여는 대표 브런치 카페로, 힙한 분위기와 푸짐한 스무디볼로 한국 여행자에게 가장 유명합니다.",
     "best_for_ko": "브런치·스무디볼",
     "sources": [
      "https://thehoneycombers.com/bali/canggu-cafes-best-coffee-brunch-lunch/",
      "https://baliexploring.com/restaurants-bars/crate-cafe-canggu/",
      "https://onbali.com/canggu/crate-cafe/"
     ],
     "status_note_ko": "분위기 대비 음식 평은 무난한 편(구글 4.2), 오전 대기 김",
     "price_usd_ko": "브런치 $3~6",
     "lat": -8.6486866,
     "lng": 115.1371844,
     "geo_precision": "exact",
     "instagram": "@cratecafe"
    },
    {
     "name": "BAKED.",
     "subcategory": "cafe",
     "area": "Berawa",
     "google_rating": null,
     "price_hint_ko": "아티장 베이커리·브런치, 중가대 (카드 결제만 가능)",
     "highlights_ko": [
      "사워도우·크루아상으로 유명한 아티장 베이커리",
      "발리 최고 수준 커피로 꼽힘",
      "스크램블 에그·샥슈카 강추",
      "배라와·프레레난 두 지점"
     ],
     "why_ko": "빵과 커피 퀄리티로 정평이 난 곳으로, 제대로 된 사워도우와 크루아상을 맛보고 싶을 때 최고입니다.",
     "best_for_ko": "브런치·베이커리",
     "sources": [
      "https://cocodevelopmentgroup.com/blog/baked-bali-the-honest-review-you-need-to-read/",
      "https://onbali.com/canggu/baked-cafe/",
      "https://thehoneycombers.com/bali/best-bakeries-in-bali/"
     ],
     "status_note_ko": "대기 길 수 있고 현금 불가(카드만)",
     "price_usd_ko": "브런치 $5~12",
     "lat": -8.6583413,
     "lng": 115.1402954,
     "geo_precision": "exact",
     "instagram": "@baked.indonesia"
    },
    {
     "name": "Milk & Madu",
     "subcategory": "cafe",
     "area": "Berawa",
     "google_rating": 4.7,
     "price_hint_ko": "브런치·화덕피자, 중가대 (가족 친화적)",
     "highlights_ko": [
      "짱구 대표 올데이 브런치 카페",
      "라이브 음악, 아늑하고 가족 친화적",
      "크루아상·스무디볼·화덕피자",
      "구글 4.7"
     ],
     "why_ko": "분위기와 음식 모두 안정적인 짱구 대표 카페로, 여유로운 브런치나 가족 단위 여행객에게 잘 맞습니다.",
     "best_for_ko": "브런치",
     "sources": [
      "https://milkandmadu.com/",
      "https://onbali.com/canggu/milk-madu-berawa/",
      "https://www.thewalkingcritic.com/blog-reviews/milk-madu-berewa/"
     ],
     "status_note_ko": "주말·공휴일 매우 붐빔, 단체는 예약 권장",
     "price_usd_ko": "브런치·피자 $5~12",
     "lat": -8.660831,
     "lng": 115.145696,
     "geo_precision": "exact",
     "instagram": "@milkandmadu"
    },
    {
     "name": "La Lucciola",
     "subcategory": "cafe",
     "area": "Petitenget",
     "google_rating": null,
     "price_hint_ko": "1인 약 25만 IDR~ (중상급 가격대), 트립어드바이저 4.5",
     "highlights_ko": [
      "쁘띠뜽엣 사원 옆 해변가 이탈리안 레스토랑",
      "스미냑 대표 선셋 다이닝 명소",
      "수제 파스타·신선한 해산물",
      "오션뷰 테이블 인기"
     ],
     "why_ko": "스미냑에서 일몰과 함께 이탈리안 정찬을 즐기기 좋은 낭만적인 곳으로, 오션뷰 테이블은 미리 예약해야 합니다.",
     "best_for_ko": "선셋 디너",
     "sources": [
      "https://www.baliholidaysecrets.com/la-lucciola/",
      "https://thebaliguideline.com/dine/seminyak/la-lucciola",
      "https://www.tripadvisor.com/Restaurant_Review-g469404-d804047-Reviews-La_Lucciola-Seminyak_Kuta_District_Bali.html"
     ],
     "status_note_ko": null,
     "price_usd_ko": "1인 $16~40",
     "lat": -8.682853,
     "lng": 115.152012,
     "geo_precision": "exact",
     "instagram": "@lalucciolabali"
    },
    {
     "name": "Tanah Lot Temple",
     "subcategory": "attraction",
     "area": "근교 (짱구에서 차로 20~30분)",
     "google_rating": null,
     "price_hint_ko": "입장료 외국인 성인 75,000 IDR, 아동 40,000 IDR (현금)",
     "highlights_ko": [
      "바다 위 바위에 세워진 발리 대표 해상 사원",
      "발리 최고의 일몰 명소 중 하나",
      "짱구에서 차로 20~30분 반나절 코스",
      "07:00~19:00 운영"
     ],
     "why_ko": "짱구에서 반나절이면 다녀오는 발리 상징 사원으로, 일몰 무렵 사원 실루엣이 압권입니다.",
     "best_for_ko": "선셋·명소",
     "sources": [
      "https://balicheapesttours.com/tanah-lot-temple.html",
      "https://www.water-sports-bali.com/tanah-lot-temple-entrance-fee/",
      "https://www.baliholidaysecrets.com/tanah-lot-temple/"
     ],
     "status_note_ko": "일몰 시간대 매우 붐빔 - 오후 4:30 이전 도착 권장, 입장료 현금만",
     "price_usd_ko": "입장 ~$5 (현금)",
     "lat": -8.6212421,
     "lng": 115.0868458,
     "geo_precision": "exact",
     "instagram": "@tanahlotid"
    },
    {
     "name": "Nuanu Creative City (Luna Beach Club)",
     "subcategory": "attraction",
     "area": "근교 (짱구에서 차로 약 15분)",
     "google_rating": null,
     "price_hint_ko": "구역별 상이 (루나 비치클럽 등 시설별 개별 이용), 단지 내 전기버스 이동",
     "highlights_ko": [
      "44헥타르 규모의 아트·웰니스 복합 문화도시",
      "2024년 오픈한 루나 비치클럽(블랙샌드·풀 2개·일몰)",
      "오로라 미디어파크 등 인터랙티브 라이트아트",
      "알파카 체험 등 가족 액티비티"
     ],
     "why_ko": "짱구 근교의 신흥 명소로, 예술·자연·비치클럽을 한 번에 즐길 수 있어 반나절 코스로 좋습니다.",
     "best_for_ko": "명소·가족·인생샷",
     "sources": [
      "https://www.nuanu.com/",
      "https://gobaligo.id/en/blog/nuanu-creative-city-luna-guide/",
      "https://elsky-bali.com/en/beach-club-luna-en/",
      "https://www.qantas.com/travelinsider/en/explore/asia/indonesia/bali/things-to-do-nuanu-bali.html"
     ],
     "status_note_ko": "계속 확장 중인 신규 단지로 일부 시설은 공사·운영 변동 가능",
     "lat": -8.6307848,
     "lng": 115.1006557,
     "geo_precision": "exact",
     "instagram": "@lunabeachclubbali"
    }
   ],
   "top_picks": {
    "beach": {
     "name": "Batu Bolong Beach",
     "reason_ko": "짱구의 서핑·카페·일몰 문화를 한자리에서 경험할 수 있는 대표 해변으로, 처음 방문한 여행자에게 가장 무난합니다."
    },
    "beachclub": {
     "name": "FINNS Beach Club",
     "reason_ko": "발리 리뷰 수 1위 비치클럽으로 파티·풀·서비스·일몰 모두 최상위 밸런스. 인생샷 위주라면 La Brisa가 대안입니다."
    },
    "cafe": {
     "name": "BAKED.",
     "reason_ko": "빵과 커피 퀄리티로 정평이 난 아티장 베이커리 겸 브런치 카페. 상징성·힙한 분위기를 원하면 Crate Cafe가 대안입니다."
    },
    "attraction": {
     "name": "Tanah Lot Temple",
     "reason_ko": "발리를 상징하는 해상 사원이자 최고의 일몰 명소로, 짱구에서 반나절 코스로 딱 좋습니다."
    }
   }
  },
  "cities": {
   "category": "cities",
   "criteria_ko": "여행자 인기·2025~2026 트렌드, 즐길거리, 맛집·카페, 해변·자연, 접근성·치안, 한국 여행자 적합도를 종합해 여러 국내외 가이드에서 반복적으로 상위로 언급되는 지역을 교차 검증해 선정했습니다. 누사페니다는 사실상 당일치기 섬 투어라는 점을 정직하게 반영했습니다.",
   "ranking": [
    {
     "rank": 1,
     "name": "Canggu",
     "name_ko": "짱구",
     "tagline_ko": "힙한 서핑 · 카페 타운",
     "why_ko": "여러 국내외 가이드가 '최근 발리에서 가장 인기 있는 지역'으로 꼽는 2026년 트렌드의 중심지로, 서퍼·디지털 노마드·힙스터가 모이는 곳입니다. SNS에서 화제인 감성 카페와 브런치 맛집, 선셋 비치클럽이 밀집해 있으면서도 풀빌라·호텔 가성비(1박 8~15만 원대)가 좋아 젊은 한국 여행자에게 특히 잘 맞습니다.",
     "best_for_ko": "카페·서핑·나이트라이프를 즐기는 2030 트렌드세터, 장기 여행자",
     "signature_ko": [
      "바뚜볼롱·에초 비치 서핑 & 초보 서핑 레슨",
      "핀스·라 브리사 선셋 비치클럽",
      "감성 카페 & 브런치 투어",
      "한적한 확장 지역 뻐르레난"
     ],
     "caution_ko": "공항~짱구 구간 등 극심한 교통체증과 빠른 관광지화로 붐비고 물가가 오르는 추세",
     "sources": [
      "https://www.tripstore.kr/blog/%EB%B0%9C%EB%A6%AC-%EC%88%99%EC%86%8C-%EC%9C%84%EC%B9%98-%EC%B6%94%EC%B2%9C-%EC%B7%A8%ED%96%A5%EB%B3%84-4%EB%8C%80-%EA%B6%8C%EC%97%AD",
      "https://www.niv.travel/posts/bali-base-canggu-ubud-uluwatu",
      "https://www.travelandtourworld.com/news/article/5zy6ynrh9nrb/"
     ]
    },
    {
     "rank": 2,
     "name": "Uluwatu",
     "name_ko": "울루와뚜",
     "tagline_ko": "절벽 위 비치클럽 · 럭셔리 선셋",
     "why_ko": "2026년 발리에서 관광객이 가장 빠르게 몰리는 상승세 지역으로, 석회암 절벽과 인도양이 만드는 극적인 풍경이 대표적입니다. 빠당빠당·믈라스띠 같은 발리 최고 수준의 해변과 사바야·선데이스 등 인기 비치클럽, 절벽 위 5성급 오션뷰 풀빌라가 몰려 있어 신혼여행·커플 럭셔리 휴양지로 한국 여행자에게 인기가 매우 높습니다.",
     "best_for_ko": "허니문·커플, 럭셔리 휴양과 서핑·선셋을 원하는 여행자",
     "signature_ko": [
      "울루와뚜 사원 + 일몰 케착 댄스",
      "빠당빠당·믈라스띠·수루반 비치",
      "사바야·선데이스 비치클럽",
      "절벽 오션뷰 풀빌라 & GWK 문화공원"
     ],
     "caution_ko": "명소가 넓게 흩어져 있어 렌터카·기사가 사실상 필수이고 시내·공항과 거리가 있음",
     "sources": [
      "https://www.bukitvista.com/blog/bali-2026-tourism-shift-where-tourists-are-flocking-uluwatu-melasti-south-kuta-explained",
      "https://www.baliholidaysecrets.com/uluwatu-bali-guide/",
      "https://kr.trip.com/blog/bali-honeymoon/"
     ]
    },
    {
     "rank": 3,
     "name": "Ubud",
     "name_ko": "우붓",
     "tagline_ko": "정글·라이스테라스 힐링 문화 중심지",
     "why_ko": "한국 가이드에서 '발리 가볼만한곳 항상 1순위'로 꼽히는 문화·자연의 중심지로, 관광 요소가 이 일대에 집약돼 있습니다. 뜨갈랄랑 계단식 논, 몽키포레스트, 짬뿌한 릿지워크와 요가·웰니스 프로그램, 정글뷰 인피니티풀 빌라가 유명하고, 우붓·누사두아·사누르와 함께 발리에서 치안이 좋은 지역으로 평가돼 힐링·허니문 여행자에게 잘 맞습니다.",
     "best_for_ko": "문화·자연·웰니스와 조용한 힐링을 원하는 커플·가족",
     "signature_ko": [
      "뜨갈랄랑 라이스테라스 & 발리 스윙",
      "몽키포레스트 · 우붓 왕궁",
      "짬뿌한 릿지워크 · 뜨거눙안 폭포",
      "정글뷰 인피니티풀 빌라 & 요가·쿠킹 클래스"
     ],
     "caution_ko": "해변이 없는 내륙 지역이라 물놀이는 어렵고 우붓 시내는 상습 정체",
     "sources": [
      "https://www.kkday.com/ko/blog/33137/asia-indonesia-bali-top-attractions",
      "https://thehoneycombers.com/bali/things-to-do-in-ubud/",
      "https://www.travelandtourworld.com/news/article/npig6othaf07/"
     ]
    },
    {
     "rank": 4,
     "name": "Seminyak",
     "name_ko": "스미냑",
     "tagline_ko": "세련된 비치클럽 · 미식 · 쇼핑",
     "why_ko": "발리에서 가장 세련된 레스토랑·부티크·유명 비치클럽이 밀집한 곳으로, 발리를 처음 찾는 여행자와 미식·쇼핑을 즐기는 커플에게 무난하게 추천되는 지역입니다. 공항에서 20~30분으로 접근성이 좋고 인프라가 잘 갖춰져 있으며, 2026년에도 발리의 대표 라이프스타일 관광지로 꾸준히 꼽힙니다.",
     "best_for_ko": "첫 발리 여행자, 미식·쇼핑·비치클럽·나이트라이프를 즐기는 커플",
     "signature_ko": [
      "포테이토 헤드 등 유명 비치클럽",
      "잘란 까유 아야(이트 스트리트) 미식·쇼핑",
      "스미냑 비치 선셋",
      "부티크 스파 & 나이트라이프"
     ],
     "caution_ko": "관광객이 많아 번잡하고 물가가 있는 편이며, 해변 자체는 남부 절벽 지역보다 평범",
     "sources": [
      "https://www.baliholidaysecrets.com/best-areas-to-stay-in-bali/",
      "https://esim.holafly.com/travel-tips/where-to-stay-in-bali/",
      "https://www.bukitvista.com/blog/bali-2026-tourism-shift-where-tourists-are-flocking-uluwatu-melasti-south-kuta-explained"
     ]
    },
    {
     "rank": 5,
     "name": "Nusa Penida",
     "name_ko": "누사페니다",
     "tagline_ko": "켈링킹 절벽 · 인생샷 섬 당일치기",
     "why_ko": "사누르에서 쾌속선으로 40~50분 떨어진 섬으로, T-렉스 형상의 켈링킹 비치는 세계에서 가장 많이 사진 찍히는 해변 중 하나로 꼽히는 발리 대표 인생샷 명소입니다. 자연·해변 경관만큼은 후보 지역 중 최고 수준이라 한국 여행자 사이에서도 '당일치기 보트 투어' 필수 코스로 인기가 높습니다.",
     "best_for_ko": "인생샷·절경을 노리는 여행자, 하루 섬 투어를 더하고 싶은 사람",
     "signature_ko": [
      "켈링킹 비치(T-렉스 절벽)",
      "엔젤스 빌라봉 · 브로큰 비치",
      "다이아몬드 비치",
      "크리스탈 베이 스노클링"
     ],
     "caution_ko": "사실상 당일치기 섬 투어 지역으로, 섬 내 도로 상태가 열악하고 켈링킹 하이킹이 가파르며 물놀이가 위험한 구간이 있음",
     "sources": [
      "https://www.waddat.com/blog/nusa-penida-day-trip-guide/",
      "https://www.tripadvisor.com/Attraction_Review-g2538506-d12396108-Reviews-Kelingking_Beach-Nusa_Penida_Bali.html",
      "https://www.kkday.com/ko/blog/33137/asia-indonesia-bali-top-attractions"
     ]
    }
   ],
   "excluded": [
    {
     "name": "Kuta",
     "name_ko": "꾸따",
     "reason_ko": "공항 접근성과 저렴한 물가는 강점이지만 예전의 명성이 퇴색해 번잡함·호객·해변 침식이 지적되고, 트렌드 면에서 바로 옆 스미냑·짱구에 밀려 TOP 5에서 제외했습니다."
    },
    {
     "name": "Jimbaran",
     "name_ko": "짐바란",
     "reason_ko": "해변 해산물 BBQ와 잔잔한 해변·석양은 매력적이지만 즐길거리가 제한적이라 독립 거점보다는 울루와뚜와 묶는 반나절 코스에 가까워 TOP 5에서 제외했습니다."
    }
   ]
  },
  "hidden": {
   "category": "hidden",
   "scene_summary_ko": "짱구·스미냑의 '나만 알고 싶은' 곳은 대부분 관광 중심가에서 북서쪽으로 15~30분 떨어진 쁘레레난 너머 세세·쩨마기(Cemagi)와 따바난 경계의 검은 모래 해변 벨트에 숨어 있다. 이 해변들은 힌두 의식이 열리는 사크리드 비치이거나 절벽 아래 좁은 진입로라 대형 투어버스가 들어오지 못해 개발이 더디고, 유명 해변의 방문객·리뷰 수에 한참 못 미치는 사람만 찾는다. 로컬 맛집과 카페는 관광 대로에서 한두 블록만 안쪽으로 들어가면 나오는 현지 소유 와룽이나, 아직 리뷰가 몇 개뿐인 세세의 작은 스페셜티 카페처럼 장기 체류자 커뮤니티 사이에서만 공유된다. 논 한가운데 표지판 없는 산책로처럼, 도심에서 도보권인데도 관광객 동선에서 살짝 벗어난 것만으로 조용함이 유지되는 곳들이다.",
   "venues": [
    {
     "name": "Seseh Beach",
     "subcategory": "beach",
     "area": "Seseh/Cemagi",
     "lat": -8.6474,
     "lng": 115.114227,
     "instagram": null,
     "google_rating": null,
     "price_hint_ko": "입장 무료 · 현지 노점에서 코코넛·빈땅·구운 옥수수 판매",
     "highlights_ko": [
      "검은 모래 위에 힌두 의식이 열리는 사크리드 비치",
      "비치클럽·카페 없이 어민·노점만 있는 날것의 로컬 분위기",
      "논밭을 지나 도착하는 드라이브와 탁 트인 일몰"
     ],
     "why_ko": "에코비치에서 차로 약 20분, 개발되지 않은 검은 모래와 어촌 풍경이 그대로 남아 있어 짱구의 번잡함을 완전히 벗어날 수 있다.",
     "why_hidden_ko": "힌두 종교의식이 열리는 신성한 해변이라 상업 개발이 억제되고, 짱구 관광객 대부분이 에코비치 북쪽까지 올라오지 않아 늘 한산하다.",
     "best_for_ko": "선셋 · 로컬 경험 · 혼자 여행",
     "sources": [
      "https://www.balitouristic.com/seseh-beach-in-cemagi-village/",
      "https://theislandgirladventures.com/2025/09/23/exploring-seseh-cemagi-and-munggu-balis-west-coast-hidden-gems/",
      "https://www.bondingexplorers.com/seseh-beach/"
     ],
     "status_note_ko": "의식이 있는 날에는 방해되지 않게 조용히 즐기고, 이안류가 있어 수영은 주의.",
     "price_usd_ko": "무료 · 노점 간식 $1~3",
     "geo_precision": "exact"
    },
    {
     "name": "Mengening Beach",
     "subcategory": "beach",
     "area": "Cemagi",
     "lat": -8.639532,
     "lng": 115.100719,
     "instagram": null,
     "google_rating": null,
     "price_hint_ko": "입장 무료 · 주차 소액",
     "highlights_ko": [
      "해식절벽 아래 검은 모래와 산호 바위·조수 웅덩이",
      "관광객 거의 없이 현지인만 일몰에 찾는 곳",
      "드라마틱한 바위 지형으로 사진 명소"
     ],
     "why_ko": "쩨마기 낮은 해식절벽 아래 숨은 검은 모래 해변으로, 세세보다도 사람이 적어 '아직도 거의 안 알려진' 순도 높은 히든 비치다.",
     "why_hidden_ko": "절벽 아래 좁은 진입로로 내려가야 해 대형 투어버스가 들어올 수 없고, 수영보다 산책·사진용이라 단체 관광 동선에서 빠져 있다.",
     "best_for_ko": "혼자 여행 · 사진 · 선셋",
     "sources": [
      "https://cinchy.life/en/blog/mengening-beach-bali",
      "https://www.airial.travel/attractions/indonesia/mengening-beach-bali-rMfDLHRM",
      "https://www.bigbogbali.com/2019/08/mengening-beach-cemagi-bali-nice-scenery-and-serene-black-sand-beach-of-cemagi-village.html"
     ],
     "status_note_ko": "바위·산호가 많아 수영엔 부적합하고, 간조 때 조수 웅덩이가 드러난다.",
     "price_usd_ko": "무료 · 주차 소액",
     "geo_precision": "exact"
    },
    {
     "name": "Nyanyi Beach",
     "subcategory": "beach",
     "area": "Nyanyi/Tabanan",
     "lat": -8.633662,
     "lng": 115.097835,
     "instagram": null,
     "google_rating": null,
     "price_hint_ko": "입장 무료 · 주차 오토바이 2,000 / 차 5,000 루피아",
     "highlights_ko": [
      "아궁 화산재로 생긴 검은 모래의 긴 해안선",
      "사람이 드물어 오래 걸어도 방해 없는 탁 트인 백사장",
      "승마·사진·조용한 일몰 감상 명소"
     ],
     "why_ko": "따나롯에서 10~15분, 짱구에서 약 15분 거리인데도 논밭에 둘러싸인 넓은 검은 모래 해변에 사람이 거의 없어 프라이빗한 느낌을 준다.",
     "why_hidden_ko": "짱구와 따바난 경계에 있어 주요 관광 동선에서 벗어나 있고, 바로 옆 유명한 따나롯에 비해 방문객과 리뷰 수가 훨씬 적다.",
     "best_for_ko": "선셋 · 산책 · 혼자 여행",
     "sources": [
      "https://www.balitouristic.com/nyanyi-beach-in-kediri-tabanan/",
      "https://bali-home-immo.com/blog/bali-attractions/where-to-go-in-nyanyi-a-hidden-gem-on-bali-s-peaceful-coast",
      "https://bali.com/places/nyanyi-beach/"
     ],
     "status_note_ko": "파도가 큰 편이라 수영보다 서핑·산책에 적합.",
     "price_usd_ko": "무료 · 주차 ~$0.5",
     "geo_precision": "exact"
    },
    {
     "name": "Warung Yess",
     "subcategory": "cafe",
     "area": "Pererenan",
     "lat": -8.642135,
     "lng": 115.129498,
     "instagram": null,
     "google_rating": 4.5,
     "price_hint_ko": "나시 짬뿌르 약 50,000~70,000 루피아",
     "highlights_ko": [
      "좁은 입구를 지나면 나오는 '시크릿 가든' 정원 좌석",
      "삼발 마따가 일품인 나시 짬뿌르",
      "MSG 없이 담백한 현지 가정식"
     ],
     "why_ko": "쁘레레난 대로변 작은 가게 입구를 지나면 분수와 초록이 가득한 정원이 펼쳐지는, 현지 소유의 숨은 와룽이다.",
     "why_hidden_ko": "관광 레스토랑이 아니라 눈에 띄지 않는 가게 앞을 지나쳐야 발견되는 구조라, 아는 사람만 찾아가는 로컬 와룽으로 남아 있다.",
     "best_for_ko": "로컬 경험 · 가성비 식사",
     "sources": [
      "https://wanderlog.com/place/details/1231879/warung-yess",
      "https://trackslesstravelled.com/best-warungs-canggu-bali/",
      "https://www.tripadvisor.com/Restaurant_Review-g1025508-d6640195-Reviews-Warung_YESS-Mengwi_Bali.html"
     ],
     "status_note_ko": null,
     "price_usd_ko": "나시짬뿌르 $3~5"
    },
    {
     "name": "Warung Babi Guling Men Lari",
     "subcategory": "cafe",
     "area": "Canggu (Padang Linjong)",
     "lat": -8.647439,
     "lng": 115.136432,
     "instagram": "@begulingmenlari",
     "google_rating": null,
     "price_hint_ko": "바비굴링 1인 세트 현지 가격(저렴)",
     "highlights_ko": [
      "바삭한 껍질과 부드러운 고기의 바비굴링(발리식 통돼지구이)",
      "밥·라와르·삼발이 함께 나오는 세트 구성",
      "현지인과 장기 체류자가 찾는 로컬 노포"
     ],
     "why_ko": "짱구 빠당린종(Padang Linjong) 교차로에 있는 바비굴링 노포로, 발리식 통돼지구이를 관광지 가격이 아닌 로컬 가격에 맛볼 수 있다.",
     "why_hidden_ko": "짱구 중심가에서 '진짜 발리'로 넘어가는 큰 교차로에 있어 관광객은 지나쳐 버리기 쉽고, 손님 대부분이 현지인과 장기 체류 외국인이다.",
     "best_for_ko": "로컬 경험 · 발리 전통 음식",
     "sources": [
      "https://www.tripadvisor.com/Restaurant_Review-g1025508-d12869920-Reviews-Babi_Guling_Men_Lari-Mengwi_Bali.html",
      "https://www.instagram.com/begulingmenlari/",
      "https://cinchy.life/en/blog/best-babi-guling-in-canggu-bali"
     ],
     "status_note_ko": "인기 메뉴는 점심에 소진되기도 하니 이른 시간 방문을 추천.",
     "price_usd_ko": "바비굴링 세트 $2~4",
     "geo_precision": "approx"
    },
    {
     "name": "Tamorra Coffee and Eatery",
     "subcategory": "cafe",
     "area": "Seseh",
     "lat": -8.6474,
     "lng": 115.1142,
     "instagram": "@tamorracafe",
     "google_rating": null,
     "price_hint_ko": null,
     "highlights_ko": [
      "세세 해변 근처의 조용한 스페셜티 커피 하우스",
      "누산타라(인도네시아산) 원두와 라떼 아트",
      "와이파이·부드러운 음악으로 노마드 작업하기 좋음"
     ],
     "why_ko": "짱구·스미냑 카페 붐에서 벗어난 세세에 자리해, 서두르지 않고 커피와 브런치를 즐기며 오래 머물기 좋은 조용한 카페다.",
     "why_hidden_ko": "트립어드바이저 리뷰가 아직 4개 남짓일 만큼 거의 안 알려졌고, 관광 대로가 아닌 한적한 세세 해변 마을에 있어 노마드·서퍼 위주로만 알음알음 공유된다.",
     "best_for_ko": "혼자 여행 · 노마드 작업 · 브런치",
     "sources": [
      "https://tamorracoffee.com/tamorra-coffee-best-cafe-seseh-bali/",
      "https://www.tripadvisor.com/Restaurant_Review-g12997583-d34127379-Reviews-Tamorra_Coffee_and_Eatery-Seseh_Mengwi_Bali.html",
      "https://weareglobaltravellers.com/2025/10/brunch-guide-seseh/"
     ],
     "status_note_ko": null,
     "geo_precision": "approx"
    },
    {
     "name": "Jogging Track Subak Uma Desa (Uma Desa Canggu)",
     "subcategory": "spot",
     "area": "Canggu (Batu Mejan/Babakan)",
     "lat": -8.628344,
     "lng": 115.148994,
     "instagram": null,
     "google_rating": 4.6,
     "price_hint_ko": "무료",
     "highlights_ko": [
      "약 1.5km 논 사이를 잇는 산책·조깅 트랙",
      "중간중간 발레 벵옹(정자)에서 쉬며 보는 일몰",
      "우붓 부럽지 않은 논 풍경인데 짱구 도심에서 도보권"
     ],
     "why_ko": "두 도로 사이 논 한가운데를 가로지르는 표지판 없는 산책로로, 관광객은 거의 없고 현지인만 조깅·산책하는 '진짜 짱구'의 조용한 쉼터다.",
     "why_hidden_ko": "Jl. Raya Batu Mejan과 Jl. Babakan Kubu 사이 논 안쪽에 숨어 있어 입구 표지판도 없고, 검색해서 일부러 찾아가지 않으면 지나치는 곳이다.",
     "best_for_ko": "선셋 · 산책 · 혼자 여행",
     "sources": [
      "https://wanderlog.com/place/details/7672098/jogging-track-subak-uma-desa",
      "https://cinchy.life/en/blog/spots-for-jogging-in-canggu-bali",
      "https://bikinigaragebali.com/en/blog/canggu-hidden-spots-to-escape-the-hustle-and-bustle/"
     ],
     "status_note_ko": "일부 현지인이 오토바이로 지나가니 주의하고, 해가 지면 어두워지므로 손전등을 챙기면 좋다.",
     "price_usd_ko": "무료"
    }
   ],
   "top_pick": {
    "name": "Seseh Beach",
    "reason_ko": "검은 모래와 힌두 사크리드 비치 특유의 고요함, 논밭 드라이브 끝의 일몰에 더해 인근 Tamorra 같은 히든 카페까지 묶어 '세세·쩨마기 해안 히든젬 벨트'의 거점이 된다. 짱구에서 차로 20분이면 닿는데도 관광객이 거의 없어 '나만 알고 싶은 곳'의 조건을 가장 잘 충족한다."
   }
  }
 },
 "hidden_stats": {
  "points": [
   {
    "key": "Canggu",
    "posts": 14213,
    "avg_eng": 2608,
    "ko": "짱구",
    "focus": true
   },
   {
    "key": "Jimbaran",
    "posts": 14216,
    "avg_eng": 2636,
    "ko": "짐바란",
    "focus": false
   },
   {
    "key": "Kuta",
    "posts": 14232,
    "avg_eng": 2595,
    "ko": "꾸따",
    "focus": false
   },
   {
    "key": "Nusa Penida",
    "posts": 14427,
    "avg_eng": 2599,
    "ko": "누사페니다",
    "focus": false
   },
   {
    "key": "Seminyak",
    "posts": 14444,
    "avg_eng": 2606,
    "ko": "스미냑",
    "focus": true
   },
   {
    "key": "Ubud",
    "posts": 14149,
    "avg_eng": 2597,
    "ko": "우붓",
    "focus": false
   },
   {
    "key": "Uluwatu",
    "posts": 14319,
    "avg_eng": 2593,
    "ko": "울루와뚜",
    "focus": false
   }
  ],
  "posts_median": 14232,
  "eng_median": 2599,
  "posts_spread_pct": 2.1,
  "eng_spread_pct": 1.7
 },
 "hidden_in_recs": [
  {
   "name": "Indian Summer Bali",
   "cat": "서핑캠프",
   "reason": "영어권 플랫폼 리뷰가 거의 없고 카카오톡·인스타그램 위주로 운영 — 한국 서퍼 커뮤니티 밖에는 거의 알려지지 않은 롱보드 전문 캠프."
  },
  {
   "name": "Pucuk Bali Gym",
   "cat": "헬스장",
   "reason": "구글 4.8(리뷰 369개)로 로컬 짐 최상위 평점인데, 리뷰 수는 유명 프리미엄 짐의 1/10 이하 — 장기체류자들의 가성비 아지트."
  },
  {
   "name": "CrossFit Canggu (Fortitude)",
   "cat": "크로스핏",
   "reason": "발리 유일의 루프탑 크로스핏 박스에 구글 5.0 — 대형 Wanderlust에 가려진 소수정예 부티크."
  },
  {
   "name": "Dee Muay Thai",
   "cat": "복싱·무에타이",
   "reason": "화려한 시설 대신 현지인·교민이 오래 다니는 스미냑 노포 짐 — 관광객 동선 밖이라 가격도 저렴."
  },
  {
   "name": "Zealot Muay Thai",
   "cat": "무에타이",
   "reason": "프로 파이터가 세세 쪽에서 운영하는 무에타이 전문관 — 대형 격투 짐 대비 거의 노출이 없다."
  }
 ]
};
